"""Document tools — Word (.docx) via python-docx, Excel (.xlsx) via openpyxl.

Markdown-lite is accepted in content:  # / ## / ###  → headings,
- / *  → bullets,  1.  → numbered,  **bold**  → bold runs.
"""
from __future__ import annotations

import json
import re
from pathlib import Path


def _p(path: str) -> Path:
    p = Path(path).expanduser()
    if not p.is_absolute():
        p = Path.cwd() / p
    return p


def _docx():
    try:
        import docx
        return docx
    except ImportError as e:
        raise RuntimeError("python-docx not installed. Run: pip install python-docx") from e


def _xlsx():
    try:
        import openpyxl
        return openpyxl
    except ImportError as e:
        raise RuntimeError("openpyxl not installed. Run: pip install openpyxl") from e


def _add_markdown_line(doc, line: str) -> None:
    if not line.strip():
        doc.add_paragraph("")
        return
    stripped = line.strip()
    if stripped.startswith("### "):
        doc.add_heading(stripped[4:], level=3)
    elif stripped.startswith("## "):
        doc.add_heading(stripped[3:], level=2)
    elif stripped.startswith("# "):
        doc.add_heading(stripped[2:], level=1)
    elif stripped.startswith(("- ", "* ")):
        _add_inline(doc.add_paragraph(), stripped[2:], style="List Bullet")
    elif re.match(r"^\d+\.\s", stripped):
        _add_inline(doc.add_paragraph(), re.sub(r"^\d+\.\s", "", stripped), style="List Number")
    else:
        _add_inline(doc.add_paragraph(), line)


def _add_inline(paragraph, text: str, style: str | None = None) -> None:
    if style:
        paragraph.style = style
    for seg in re.split(r"(\*\*.+?\*\*)", text):
        if not seg:
            continue
        if seg.startswith("**") and seg.endswith("**") and len(seg) > 4:
            paragraph.add_run(seg[2:-2]).bold = True
        else:
            paragraph.add_run(seg)


def _parse_sections(sections) -> dict:
    if isinstance(sections, str):
        try:
            sections = json.loads(sections)
        except json.JSONDecodeError as e:
            raise ValueError(f"sections must be a JSON object: {e}")
    if not isinstance(sections, dict) or not sections:
        raise ValueError("sections must be a non-empty {name: content} mapping")
    return sections


# ---------------------------------------------------------------- word ---
def create_word_doc(path: str, title: str, content: str) -> str:
    """Create a .docx from a title + markdown-lite content."""
    docx = _docx()
    p = _p(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    doc = docx.Document()
    doc.add_heading(title, level=0)
    for line in content.splitlines():
        _add_markdown_line(doc, line)
    doc.save(str(p))
    return f"Created: {p} ({p.stat().st_size} bytes)"


def read_word_doc(path: str) -> str:
    """Extract all text from a .docx, preserving heading/bullet structure."""
    docx = _docx()
    p = _p(path)
    if not p.exists():
        raise FileNotFoundError(f"document not found: {p}")
    doc = docx.Document(str(p))
    lines = []
    for para in doc.paragraphs:
        style = (para.style.name or "") if para.style else ""
        text = para.text.strip()
        if not text:
            continue
        if "Heading 1" in style:
            lines.append(f"# {text}")
        elif "Heading 2" in style:
            lines.append(f"## {text}")
        elif "Heading 3" in style:
            lines.append(f"### {text}")
        elif "List" in style:
            lines.append(f"- {text}")
        else:
            lines.append(text)
    for table in doc.tables:
        for row in table.rows:
            lines.append(" | ".join(c.text.strip() for c in row.cells))
    return "\n".join(lines) if lines else "(empty document)"


def append_to_word_doc(path: str, content: str) -> str:
    """Append markdown-lite content to an existing .docx."""
    docx = _docx()
    p = _p(path)
    if not p.exists():
        raise FileNotFoundError(f"document not found: {p}")
    doc = docx.Document(str(p))
    for line in content.splitlines():
        _add_markdown_line(doc, line)
    doc.save(str(p))
    return f"Appended to {p} ({p.stat().st_size} bytes)"


def create_project_report(path: str, title: str, sections: dict) -> str:
    """Create a formatted project report: title, date, TOC, sectioned body,
    page breaks between sections."""
    import datetime

    docx = _docx()
    secs = _parse_sections(sections)
    p = _p(path)
    p.parent.mkdir(parents=True, exist_ok=True)

    doc = docx.Document()
    doc.add_heading(title, level=0)
    doc.add_paragraph(f"Generated by FRIDAY — {datetime.datetime.now():%d %B %Y, %H:%M}")
    doc.add_heading("Table of Contents", level=1)
    for i, name in enumerate(secs.keys(), 1):
        _add_inline(doc.add_paragraph(), f"{i}. {name}", style="List Number")
    doc.add_page_break()

    for i, (name, body) in enumerate(secs.items()):
        doc.add_heading(f"{i + 1}. {name}", level=1)
        for line in str(body).splitlines():
            _add_markdown_line(doc, line)
        if i < len(secs) - 1:
            doc.add_page_break()

    doc.save(str(p))
    return f"Report created: {p} ({len(secs)} sections, {p.stat().st_size} bytes)"


# ---------------------------------------------------------------- excel ---
def create_excel(path: str, data: str, sheet_name: str = "Sheet1") -> str:
    """Create an .xlsx. data is a JSON list of rows: [["a","b"],[1,2]] — first
    row becomes a bold header."""
    openpyxl = _xlsx()
    try:
        rows = json.loads(data)
    except json.JSONDecodeError as e:
        raise ValueError(f"data must be a JSON list of rows, e.g. [[\"a\",\"b\"],[1,2]]: {e}")
    if not isinstance(rows, list):
        raise ValueError("data must be a list of rows")
    p = _p(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_name
    for row in rows:
        ws.append(row if isinstance(row, list) else [row])
    for cell in ws[1]:
        cell.font = openpyxl.styles.Font(bold=True)
    ws.freeze_panes = "A2"
    wb.save(str(p))
    return f"Created: {p} ({len(rows)} rows)"


def read_excel(path: str, sheet_name: str | None = None) -> str:
    """Read an .xlsx sheet as a pipe-separated table."""
    openpyxl = _xlsx()
    p = _p(path)
    if not p.exists():
        raise FileNotFoundError(f"workbook not found: {p}")
    wb = openpyxl.load_workbook(str(p), data_only=True)
    ws = wb[sheet_name] if sheet_name and sheet_name in wb.sheetnames else wb.active
    lines = []
    for row in ws.iter_rows(values_only=True):
        cells = ["" if v is None else str(v) for v in row]
        if any(c.strip() for c in cells):
            lines.append(" | ".join(cells))
    if not lines:
        return f"Sheet '{ws.title}' is empty."
    return f"Sheet '{ws.title}' ({len(lines)} rows):\n" + "\n".join(lines[:500])


def append_excel_row(path: str, sheet_name: str, row_data: str) -> str:
    """Append one row (JSON list) to an existing sheet."""
    openpyxl = _xlsx()
    try:
        row = json.loads(row_data)
    except json.JSONDecodeError as e:
        raise ValueError(f"row_data must be a JSON list, e.g. [\"a\",1]: {e}")
    if not isinstance(row, list):
        raise ValueError("row_data must be a JSON list")
    p = _p(path)
    if not p.exists():
        raise FileNotFoundError(f"workbook not found: {p}")
    wb = openpyxl.load_workbook(str(p))
    ws = wb[sheet_name] if sheet_name in wb.sheetnames else wb.active
    ws.append(row)
    wb.save(str(p))
    return f"Appended row to '{ws.title}' in {p}"


_DECLARATIONS: list[dict] = [
    {
        "name": "create_word_doc",
        "description": "Create a Word .docx document from a title and markdown-lite content (# headings, - bullets, **bold**). Returns the path.",
        "parameters": {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Output .docx path"},
                "title": {"type": "string"},
                "content": {"type": "string", "description": "Body text; use # / ## / ### for headings, - for bullets, **bold**"},
            },
            "required": ["path", "title", "content"],
        },
    },
    {
        "name": "read_word_doc",
        "description": "Extract all text from a .docx preserving heading/bullet structure.",
        "parameters": {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
        },
    },
    {
        "name": "append_to_word_doc",
        "description": "Append markdown-lite content to an existing .docx.",
        "parameters": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "content": {"type": "string"},
            },
            "required": ["path", "content"],
        },
    },
    {
        "name": "create_project_report",
        "description": "Create a full project report .docx: title, date, table of contents, one section per entry, page breaks between sections.",
        "parameters": {
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Output .docx path"},
                "title": {"type": "string"},
                "sections": {
                    "type": "object",
                    "description": "Ordered mapping of section name → body text (markdown-lite).",
                },
            },
            "required": ["path", "title", "sections"],
        },
    },
    {
        "name": "create_excel",
        "description": "Create an Excel .xlsx from a JSON list of rows. First row becomes a bold header.",
        "parameters": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "data": {"type": "string", "description": 'JSON list of rows, e.g. [["Name","Qty"],["Widget",3]]'},
                "sheet_name": {"type": "string"},
            },
            "required": ["path", "data"],
        },
    },
    {
        "name": "read_excel",
        "description": "Read an .xlsx sheet as a pipe-separated table.",
        "parameters": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "sheet_name": {"type": "string", "description": "optional sheet name; defaults to the active sheet"},
            },
            "required": ["path"],
        },
    },
    {
        "name": "append_excel_row",
        "description": "Append one row (JSON list) to a sheet in an existing .xlsx.",
        "parameters": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "sheet_name": {"type": "string"},
                "row_data": {"type": "string", "description": "JSON list, e.g. [\"Widget\",3,9.99]"},
            },
            "required": ["path", "sheet_name", "row_data"],
        },
    },
]


def register_tools(registry) -> None:
    for d in _DECLARATIONS:
        registry.register_tool(d["name"], globals()[d["name"]], d)
